### PR TITLE
Awesome resources for mobile developers and marketing experts

### PR DESCRIPTION
**Pull request by alec-c4**
Added link to the repo with awesome resources for mobile developers and marketing experts

### CODE REVIEW

**Comment by tkovs** [comment]
Read this, please.

[Contributing](https://github.com/bayandin/awesome-awesomeness/blob/master/CONTRIBUTING.md)

**Comment by alec-c4** [comment]
@tkovs updated description

**Comment by m1guelpf** [comment]
@alec-c4  Your PR needs manual merge. This means that we can't merge it automatically.
This process is very slow.
If you want to help to speed it up, please open another pull request, add the changes and, when you finish, close this and ping me in the new one.
Thank you!

**Comment by m1guelpf** [comment]
Manually merged

**Pull request closed without merging**
