### PR TITLE
Add telegram awesome

### PR DESCRIPTION
**Pull request by ebertti**
Collection great groups, channels, bots and libraries for Telegram

### CODE REVIEW

**Comment by jpedrojpedro** [comment]
👍

**Comment by felliper** [comment]
:+1:

**Comment by blopa** [comment]
👍

**Comment by FlavioAugusto** [comment]
:+1:

**Comment by nicolasteodosio** [comment]
:+1:

**Comment by Philosoft** [comment]
Guys, you can add 👍 reaction to topic itself, no need to spam comments with just 1 emoji (it's already 4 month since this is available [more info](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)).

btw, seems like it's a dead repo now for a loooong time https://github.com/bayandin/awesome-awesomeness/issues

**Pull request merged**
