### PR TITLE
Add awesome graph embedding repository.

### PR DESCRIPTION
**Pull request by benedekrozemberczki**
The repository is an exhaustive list of graph representation learning research papers with reference implementations. The machine learning task is to create representations of whole graphs from a database e.g. molecules, financial transaction graphs etc. It covers factorization models, graph kernels, statistical fingerprints and deep learning.

**[https://github.com/benedekrozemberczki/awesome-graph-embedding]**

**[The repository is an exhaustive list of graph representation learning research papers with reference implementations. The machine learning task is to create representations of whole graphs from a database e.g. molecules, financial transaction graphs etc. It covers factorization models, graph kernels, statistical fingerprints and deep learning.]**

# By submitting this pull request I confirm I've read and complied with the below requirements.

Failure to properly do so will just result in the pull request being closed and everyone's time wasted. Please read it twice. Most people miss many things.

- [x ] I have read and understood the [contribution guidelines](https://github.com/bayandin/awesome-awesomeness/blob/master/CONTRIBUTING.md).
- [ x] This pull request has a descriptive title. For example, `Add [Name of List]`, not `Update readme.md` or `Add an awesome list`.
- [ x] The list I added **has been around for at least 20 days**,
- [ x] The list I added is a non-generated Markdown file in a GitHub repo,
- [ x] The list I added is not a duplicate

### CODE REVIEW

**Comment by benedekrozemberczki** [comment]
I do not get what is the error with Travis.

**Comment by benedekrozemberczki** [comment]
Is it going to be be added?

**Comment by m1guelpf** [comment]
@benedekrozemberczki It's now in the list

**Comment by benedekrozemberczki** [comment]
@m1guelpf I cannot see it and the markdown form for the pull requests was overwritten. My bad I suppose on that.

**Comment by benedekrozemberczki** [comment]
@m1guelpf I do not think so. Actually the pull request form was overwritten.

**Pull request merged**
