### PR TITLE
Added awesome-no-login-web-apps

### PR DESCRIPTION
**Pull request by aviaryan**
https://github.com/aviaryan/awesome-no-login-web-apps

Curated list of awesome web apps that work without requesting you to create an account.

cc @m1guelpf #279

### CODE REVIEW

**Comment by aviaryan** [comment]
@m1guelpf I am not sure about the name of listing I have chosen >  `Web Apps (that work without login)` . 
Is it ok or we need something different ?

Other names I had in mind - 
* No Login
* No Login Web Apps

**Comment by m1guelpf** [comment]
@aviaryan You colud put No login web apps or Web apps (that work without login).
I leave it up to you.
Also, thank you for helping!

**Comment by KleoPetroff** [comment]
I like "No Login Web Apps" better. Leaving the final decision to @aviaryan. :slightly_smiling_face:

**Comment by m1guelpf** [comment]
@aviaryan Changed it to "No Login Web Apps" for popular vote, change it back if you want

**Comment by KleoPetroff** [comment]
@aviaryan great! Can you please move it to its right lexicographical position. When done, the PR will be ready to merge.

**Comment by m1guelpf** [comment]
@aviaryan @KleoPetroff That was my fault, it is in order now

**Comment by aviaryan** [comment]
@m1guelpf @KleoPetroff "No Login Web Apps" works good for me.  :+1:

**Pull request merged**
