### PR TITLE
Add awesome-newsletters

### PR DESCRIPTION
**Pull request by webpro**
It's just front-end + Node at this moment, but should grow.

### CODE REVIEW

**Comment by testbrian** [comment]
Also 
http://blog.alteroot.org/articles/2015-05-21/awesome-mailinglists.html
https://netguru.co/blog/web-mobile-development-newsletters

**Comment by webpro** [comment]
Thanks! Didn't know about them, will go through them and see what to add. Feel free to PR. I think a list on GitHub is awesome, as people can contribute/maintain.

**Comment by testbrian** [comment]
Agree :)

**Comment by m1guelpf** [comment]
@webpro  Your PR needs manual merge. This means that we can't merge it automatically.
This process is very slow.
If you want to help to speed it up, please open another pull request, add the changes and, when you finish, close this and ping me in the new one.
Thank you!

**Comment by m1guelpf** [comment]
Manually merged

**Pull request closed without merging**
